# Numpy

[Numpy](https://www.numpy.org/) is the foundation of most of what you will do with scientific python. Modules like [scipy](https://www.scipy.org/) and [pandas](https://pandas.pydata.org/) are built on top of numpy, and it is the linga franca for most numerical work in python.

In [1]:
import numpy as np

When you are first introduced to python, one of the big selling points is that it isn't statically typed. You can do things like

In [2]:
a = 1
a = 'apple'
print(a)

apple


And you don't get complaints from python about a being an integer. This is a _big_ advantage for python, and it works with collections as well

In [3]:
myList = [1, 3., 'Ian', [range(3)], {'not': 'a good idea'}]
myList

[1, 3.0, 'Ian', [range(0, 3)], {'not': 'a good idea'}]

Lists in python are about as general as they could be. This is very flexible and it lets you do some fancy things, but it has a price. The Python interpreter can't make any assumptions about what will come next in a list; everything has to be treated as a generic object. Python does a good job of hiding the complexity of doing this, but as the lists get longer and more complex the overhead gets larger, and eventually perfomance becomes unacceptable.

One solution to this is to use a statically typed language like C[<sup>1</sup>](#fn1 "footnote and tooltip 1"). There the burden of figuring out object types is left to the programmer, and the compiler can be much more efficient operating on them. A good example would be an array of `double`s. In memory, these will be allocated contiguously so when you need to jump to the 1402th double, you can do it with very simple arithmetic. Python has a much harder time because the memory allocated for your list could be a horrible mixture of all the different things you've stuffed in there. 

## The `ndarray`

Numpy attempts let you keep the advantages of Python without sacraficing the speed of static typing by adding the concept of homogenous collections to python: `ndarray`s. The `ndarray` is the foundational concept in numpy, it is an array object which represents a multidimensional, homogeneous array of fixed-size items and most commonly these items will be numbers.

In [4]:
%%timeit
for i in range(1000000):
    i*i

79.2 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit np.arange(1000000)**2

5.32 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


`ndarray`s look like python lists, but they are fundamentally different, e.g.

In [6]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
na = np.array([1, 2, 3, 4])
nb = np.array([5, 6, 7, 8])
na + nb

array([ 6,  8, 10, 12])

`numpy` was able to assume that the things in the `ndarray` were the compatible types and vectorize the addition, if we want the same thing with python lists, we have to jump through some hoops

In [8]:
[ i + j for i, j in zip(a, b) ] 

[6, 8, 10, 12]

Let's take a look at what makes up an `ndarray`.

In [ ]:
na = np.array([1,2,3,4,5])
na

In [9]:
attr_names = [attr_name for attr_name in dir(np.ndarray)
              if not callable(getattr(np.ndarray, attr_name)) 
              and not attr_name[:2] == '__']

attr_help = {a : getattr(np.ndarray, a).__doc__.split('\n')[0] for a in attr_names}

In [10]:
attr_help

{'T': 'The transposed array.',
 'base': 'Base object if memory is from some other object.',
 'ctypes': 'An object to simplify the interaction of the array with the ctypes',
 'data': "Python buffer object pointing to the start of the array's data.",
 'dtype': "Data-type of the array's elements.",
 'flags': 'Information about the memory layout of the array.',
 'flat': 'A 1-D iterator over the array.',
 'imag': 'The imaginary part of the array.',
 'itemsize': 'Length of one array element in bytes.',
 'nbytes': 'Total bytes consumed by the elements of the array.',
 'ndim': 'Number of array dimensions.',
 'real': 'The real part of the array.',
 'shape': 'Tuple of array dimensions.',
 'size': 'Number of elements in the array.',
 'strides': 'Tuple of bytes to step in each dimension when traversing an array.'}

By knowing these attributes, numpy can use some of the same tricks that statically typed languges use because the Python interpreter can now infer the memory layout.

numpy has some convenience methods for creating new ndarrays. As you saw above, one way to create an ndarray is to pass a list with the values to `np.array`. Here are some others...

Using np.array directly

In [13]:
a1 = np.array([0, 1, 1, 2, 3, 5, 8, 13])
a1

array([ 0,  1,  1,  2,  3,  5,  8, 13])

`np.arange` will generate numbers between limits

In [14]:
a2 = np.arange(0, 100)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
a22 = np.arange(0, 10, dtype=float)
a22

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

`np.linspace` is extremely useful, you tell it where to start and stop and how many samples you need and linspace does the rest. Here we will create numbers 100 numbers between 0 (inclusive) and 1, linearly spaced

In [17]:
li1 = np.linspace(0, 1, 20)
li1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

The `np.zeros` function will generate an `ndarray` full of zeros. The first argument is the shape which you can give as an integer (for 1d arrays) or a sequence (for n-dimensional arrays). You can also pass the `dtype=` argument to tell it what type of number you are looking for.

In [19]:
# z1 100 integer zeros
z1 = np.zeros(100, dtype=int)

# z2 a 5,5 array of float64 zeros
z2 = np.zeros((5, 5), dtype=float)
z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

The `np.ones` function does something similar, but with unit value

In [20]:
# o1 100 integers ones
o1 = np.ones(100, dtype='float64')
o1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# o2 a 5x5 ndarray of complex128 one values. First argument is shape sequence
o2 = np.ones((5, 5), dtype='complex128')
o2

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

The `np.eye` function generates a 2D array with ones down the diagonal, zeros elsewhere

In [22]:
# e1 a 5x5 array with ones down the diagonal
e1 = np.eye(5, dtype=np.float64)
e1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

We'll come back to the `numpy.random` module later on, but it has some useful convenience methods. `np.random.randint` returns random integers. Take a look at the help on the method then create a name `r1` with an array of `4x5` random numbers between `0` and `10`.


In [23]:
# r1 a 4x5 array of random integers between 0 & 10, 
np.random.randint(0, 10, size=(4, 5))

array([[4, 9, 9, 5, 7],
       [5, 5, 1, 1, 0],
       [1, 1, 9, 4, 1],
       [3, 4, 2, 2, 4]])

## Indexing and Slicing

Now that we have some `ndarray`s to play with, lets look at using them. Of course, `ndarray`s are zero indexed


In [24]:
# First element of a2
a2[0]

0

The usual negative number notation works for counting from the end

In [27]:
# 2nd to last element of a2
a2[-2]

98

We can update `ndarray` in place by index


In [29]:
a2[-1] = 0
a2[-1]

0

Slicing returns subarrays of the original `ndarray`. Crucially it does this inexpensively by returning a "view" on the data rather than copying it. This is much more efficient and relies on numpy is using it's knowledge of the memory layout to return only the things you ask for. This is a general tactic used by numpy, if it _can_ return a view rather than a copy it _will_! If you really need a copy, try the `.copy()` method on `ndarrays`.

Slicing uses the same notation as core python: `[start:stop:step]` where `start` is inclusive and `stop` is exclusive.

In [30]:
# Values between 3 and 19 of a2
a2[3:19]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [31]:
# Every third value between 3 and 19
a2[3:19:3]

array([ 3,  6,  9, 12, 15, 18])

Using negative is allowed for all three parts of the slice, but for the step you have to think a bit

In [32]:
# Values between -10 and -2
a2[-10:-2]

array([90, 91, 92, 93, 94, 95, 96, 97])

Notice that the first argument of the slice is still inclusive and the second is not. If we omit a value when specifying the slice `start` defaults to 0, `end` defaults to the last element and `step` defaults to 1.

In [34]:
a2[-2:-10:-1]

array([98, 97, 96, 95, 94, 93, 92, 91])

For multi-dimensional arrays the indexing notation is similar

In [35]:
b = np.arange(100)
b.shape = (10, 10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

How about row 0, column 3 (remember python is 0 indexed)

In [36]:
b[0,3]

3

In [37]:
b[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

Or the fifth column of the first two rows

In [38]:
b[0:2, 4]

array([ 4, 14])

In [39]:
b[0:2, 4:6]

array([[ 4,  5],
       [14, 15]])

In [40]:
b[::2, 9]

array([ 9, 29, 49, 69, 89])

## Reshaping Arrays

Sometimes it is convenient to reshape arrays. I did this above by setting the `.shape` attribute but numpy arrays also have a reshape method.

In [41]:
c = np.arange(27)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

`reshape` expects a sequence as the first argument (e.g. a tuple) so

In [42]:
d = c.reshape((3, 9))
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

Reshaping isn't enough to provoke numpy to copy the data, all it needs to do is make a new view on the same data

In [47]:
d.base is c

True

Another common reshaping task is to add dimension(s) to an existing array. numpy has a special `newaxis` object for this task. This is a powerful idea when combined with numpy's broadcasting rules (see below).

In [48]:
e = np.arange(10)

# 10 x 1
e[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
# 1 x 10
e[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
# 1 x 1 x 10
e[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

## Stacking & Splitting ndarrays

You can combine general ndarrays with the `np.concatenate` and split them with `np.split`. There are also a number of convenience methods for commonly used shapes.

 * `hstack`
 * `vstack`
 * `hsplit`
 * `vsplit`

`hstack` is short for horizontal stack

In [51]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

np.hstack((a, b))

array([1, 2, 3, 4, 4, 3, 2, 1])

For `2D` arrays this means we are joining columns

In [56]:
a[np.newaxis, :].T

array([[1],
       [2],
       [3],
       [4]])

In [55]:
# 4 x 1 & 4 x 1
np.hstack((a[np.newaxis, :].T, b[np.newaxis, :].T))

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [54]:
# 1 x 4 & 
# 1 x 4
np.vstack((a, b))

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
# 4 x 1 & 
# 4 x 1
np.vstack((a[:, np.newaxis], b[:, np.newaxis]))

In higher dimensions `concatenate` or `stack` should do what you need, but you need to manually tell it which axis to use for the stacking.

`np.split` goes in the opposite direction. It will try to produce sub-arrays of equal size. Again there are `hsplit` and `vsplit` variants for common use cases.

In [57]:
np.split(np.arange(64).reshape((8, 8)), 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])]

In [58]:
np.split(np.arange(64).reshape((8, 8)), 2, axis=1)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43],
        [48, 49, 50, 51],
        [56, 57, 58, 59]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47],
        [52, 53, 54, 55],
        [60, 61, 62, 63]])]

## Universal Functions (ufuncs)

The real reason for using numpy is so you can do numerical operations, _quickly_. Python uses a concept called `ufuncs` or universal function. A ufunc is a function which operates on `ndarrays` element-by-element. More formally, a `ufunc` is a vectorized wrapper around a function which can do a transformation on an `ndarray` and produces another `ndarray`. This element by element behaviour is fundamentally different from the usual python behaviour.

The key to writing fast numeric python code is: **Avoid for & while loops as far as you can, use numpy ufuncs as far as possible**


Lets start with basic arithmetic operations. Numpy can use it's internal broadcasting to do these quickly and efficiently

The usual operations are available

  * +: addition
  * -: subtraction
  * *: multiplication
  * /: division
  * //: integer division
  * **: power operator
  * %: modulo

Remember operations are element by element, and you can build up more complicated expressions as you go

In [60]:
la = np.linspace(0, 1, 10)

(la ** 2 + la) / (la + 1)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Example**: Try to calculate the terms of this sum as an `ndarray`
$$
\sqrt{12}\sum_{k=0}^{10}\frac{(-3)^{-k}}{2k+1}
$$

_Hints_: Start with `np.arange(11)` and think term by term, summing at the end

In [69]:
k = np.arange(11, dtype=float)
np.sqrt(12) * np.sum((-3)**(-k) / (2*k + 1))

3.141593304503081

The operators we were using `+,-,/,...` actually correspond to functions (`ufuncs`)

|operator|function|description|
|--------|--------|-----------|
| + | np.add | Addition |
| - | np.subtract | Subtraction |
| - | np.negative | Unary negation |
| * | np.multiply | Multiplication |
| / | np.division | Ordinary floating point division |
| // | np.floor_divide | floor (integer) division |
| % | np.mod | Modulo/Remainder division |

You can use either syntax, but in the function notation there are lots more functions to play with e.g.

| function | description |
|----------|-------------|
| np.sin   | sin function |
| np.cos   | cos function |
| np.tan   | tan function |
| np.abs   | absolute value |
| np.exp   | exponential |
| np.log   | natural log |
| np.log2  | log base 2 |
| np.log10 | log base 10 |
|  ...     |    ...      |


In [70]:
p1 = np.linspace(0, 2*np.pi, 25)
p2 = np.sin(p1)
p2

# p2 sin of p1

array([ 0.00000000e+00,  2.58819045e-01,  5.00000000e-01,  7.07106781e-01,
        8.66025404e-01,  9.65925826e-01,  1.00000000e+00,  9.65925826e-01,
        8.66025404e-01,  7.07106781e-01,  5.00000000e-01,  2.58819045e-01,
        1.22464680e-16, -2.58819045e-01, -5.00000000e-01, -7.07106781e-01,
       -8.66025404e-01, -9.65925826e-01, -1.00000000e+00, -9.65925826e-01,
       -8.66025404e-01, -7.07106781e-01, -5.00000000e-01, -2.58819045e-01,
       -2.44929360e-16])

In [71]:
q1 = np.linspace(0, 1, 10) + np.linspace(1, 2, 10)*1j
q1

array([0.        +1.j        , 0.11111111+1.11111111j,
       0.22222222+1.22222222j, 0.33333333+1.33333333j,
       0.44444444+1.44444444j, 0.55555556+1.55555556j,
       0.66666667+1.66666667j, 0.77777778+1.77777778j,
       0.88888889+1.88888889j, 1.        +2.j        ])

In [72]:
np.abs(q1)

array([1.        , 1.11665285, 1.24225999, 1.37436854, 1.5112745 ,
       1.65178542, 1.79505494, 1.94047213, 2.08758825, 2.23606798])

## Aggregate Functions

Aggregate functions take an `ndarray` and reduce it along one (or more) axes. An example would be taking an array of numbers and calculating the mean value...

In [73]:
r1 = np.linspace(0, 10, 100)
r1.mean()

5.0

But there are lots of aggregate functions

  * `min`: Minumum value
  * `max`: Maximum value
  * `sum`: Sum values
  * `prod`: Product of values
  * `mean`: Arthmetic mean
  * `std`: Standard deviation
  * `var`: Variance
  * `argmin`: indices of the minimum value
  * `argmax`: indices of the maximum value
  * `all`: is a condition true in all elements
  * `any`: is a condition true in any elements
  * `allclose`: All the values are within a small tolerance **really useful!**
  
  The default is to reduce along all axes, if you want to reduce along a specific axis you can pass that as an argument (the axes you specify are the ones which get squashed) 

In [74]:
s1 = np.arange(50)
s2 = s1.reshape(5,10)
s2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
s2.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5])

In [76]:
s2.argmax(axis=0)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [77]:
np.argmax(s2, axis=0)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [ ]:
np.unravel_index(s2.argmax(), s2.shape)

For binary operations (e.g. addition) you can also do reduction, so starting from

[1, 3, 5, 7, 9]

`np.add.reduce` will add 1 to 3, add that to 5 and so on, ...

In [79]:
t1 = np.arange(1, 10, 2)
np.add.reduce(t1)

25

## Fancy Indexing

Fancy is the idea of using another array of indices to access your data, it is useful when the combinations you want to select become a bit more complicated than you can handle with slicing. A typical case would be where you are evaulating some condition for all elements (e.g. t1 < 5). It allows a lot of flexibility, but the downside of that flexibility is it will usually return a copy of the array rather than a view of the original data.

In [80]:
v1=np.arange(27)[::-1]
v1

array([26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
        9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [81]:
v1[[1, 4, 6]]

array([25, 22, 20])

In [82]:
v2 = v1.reshape(3,9)
v2

array([[26, 25, 24, 23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12, 11, 10,  9],
       [ 8,  7,  6,  5,  4,  3,  2,  1,  0]])

In higher dimensions think of zipping together the arguements, e.g. 0-th row, 4th column

In [83]:
v2[[0, 1, 1], [3, 7, 8]]

array([23, 10,  9])

In [84]:
v2 > 10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [85]:
v2[v2 > 10]

array([26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

*N.B. Fancy indexing usually creates copies of the `ndarray` because you usually can't reconstruct the selection with simple algebra*

## Broadcasting

`numpy` is at it's most efficient when it is operating element by element, but not all arrays are the same size. To work around this, `numpy` implements a set of rules under the name of `broadcasting` to make `ndarray`s conform whenever possible. This is great news; it means you don't have to worry about doing that yourself, but it is important to understand the rules so that you know how `numpy` will behave when combining differnt shaped `nbdarrays`. To get the idea, think of
```python
np.arange(10) * 5
```
`numpy` wants to operate element-by-element, but `5` isn't an `ndarray`, it's just a number. If we could prompte 5 to be a `1d` narray and put 5's in in every place `numpy` would be happy. This is the basic idea of broadcasting, in summary

1. Given two arrays of different dimensions, prepend 1, to the shape of the smaller array
1. Dimensions of size 1 are repeated (without copying)


In [86]:
a = np.arange(15)
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

If I want to multiply these two `ndarray`s, `b` has the smaller dimensions (1 vs. 2) so a dimension of length one will be prepended to `b`. `b` will then be repeated 3 times to conform with the shape of a.

In [89]:
a * b

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56]])

Just to be explicit, that operation does something lie

In [90]:
btmp = np.repeat(b[np.newaxis, :], 3, axis=0)
a *  btmp

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56]])

In [91]:
btmp

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Random

Numpy has a few important submodules but `np.random` is probably the most important. As you might expect, it lets you work with random numbers but in addition to simple random numer generators, it can sample from different distributions (30+ available), handle permutations and do lots of other handy things.

`numpy.random` uses the concept of a `Generators` to implement sampling. The idea is you create a generator object then call methods on that generator to sample from the various distributions. The original `Generator` will normally get it's entropy from a (hopefully reliable) source then you can keep asking it for the `__next__` random elements distributed however you need.

(The generator interface to `numpy.random` is relatively recent, occasionally you will still see me explicity call functions of the submodule because I'm a slow learner).

In [92]:
rng = np.random.default_rng(47)

In [101]:
np.random.default_rng?

Docstring:
Construct a new Generator with the default BitGenerator (PCG64).

Parameters
----------
seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
    A seed to initialize the `BitGenerator`. If None, then fresh,
    unpredictable entropy will be pulled from the OS. If an ``int`` or
    ``array_like[ints]`` is passed, then it will be passed to
    `SeedSequence` to derive the initial `BitGenerator` state. One may also
    pass in a `SeedSequence` instance.
    Additionally, when passed a `BitGenerator`, it will be wrapped by
    `Generator`. If passed a `Generator`, it will be returned unaltered.

Returns
-------
Generator
    The initialized generator object.

Notes
-----
If ``seed`` is not a `BitGenerator` or a `Generator`, a new `BitGenerator`
is instantiated. This function does not manage a default global instance.

Examples
--------
``default_rng`` is the recommended constructor for the random number class
``Generator``. Here are several ways 

Here we've seeded the `Generator` with a specific value so the results are reporoducible but normally you would just call `np.random.default_rng()` to get a random value from the OS. Now we can sample from various distributions

In [93]:
rng.normal(5.0, 1.0, (64, 64))

array([[4.33356306, 5.09745097, 3.10035317, ..., 4.2624879 , 3.87568917,
        5.5543839 ],
       [5.73345648, 3.49665224, 5.58720581, ..., 5.23648767, 3.67712946,
        4.68678973],
       [4.9807106 , 4.99034228, 6.48206409, ..., 5.72489343, 3.62803609,
        5.15625969],
       ...,
       [4.7901849 , 3.85305691, 6.53701888, ..., 3.04381142, 5.28486458,
        4.90437718],
       [5.64158217, 5.53891296, 5.15936507, ..., 3.9880396 , 5.50389762,
        4.31922717],
       [1.46744246, 4.96496066, 3.49042918, ..., 4.76275371, 6.46497392,
        4.39969841]])

The binomial distribution

In [94]:
rng.binomial(10, .5, size=20)

array([9, 2, 5, 6, 4, 4, 6, 5, 4, 6, 8, 4, 6, 4, 3, 5, 5, 4, 4, 3])

5 random integers between 10 and 20

In [95]:
rng.integers(10, 20, 5)

array([12, 18, 15, 17, 13])

`np.random` also has functions for shuffling arrays in-place (`np.shuffle`) and selecting elements at random from `ndarrays` (`np.choice`)

In [96]:
a = np.arange(10)
np.random.shuffle(a)
a

array([9, 8, 1, 0, 4, 5, 3, 7, 2, 6])

In [98]:
a = np.arange(10)
np.random.choice(a, 3, replace=False)

array([1, 9, 2])

You can also weight the selections in `np.choice` with probabilities. e.g. Here are the letter frequencies of ordinary english text.

In [99]:
letter_freq = {' ': 0.19266420666588144,
 'e': 0.09680968984305797,
 't': 0.07140241019840815,
 'a': 0.06361581392196947,
 'o': 0.06183938572048604,
 'i': 0.05349452953695084,
 'n': 0.0521037201730283,
 'h': 0.051232447485652234,
 's': 0.049280151278754014,
 'r': 0.04524648142979075,
 'd': 0.03375374929612461,
 'l': 0.03124157971419029,
 'u': 0.02392934301198968,
 'm': 0.021518821910249234,
 'w': 0.020208685943305965,
 'c': 0.02004895261728702,
 'f': 0.016262143363080305,
 'y': 0.016250849087503207,
 'g': 0.013559584564274916,
 'p': 0.012933559003715817,
 ',': 0.012259129404969158,
 '.': 0.01200420147051468,
 'b': 0.011160357738111564,
 'v': 0.0076220225466009876,
 'k': 0.006392559976636984,
 'x': 0.001353699601312072,
 'j': 0.0008260955850676769,
 'q': 0.0006663622590487316,
 'z': 0.00031946665203789066
}

We can use those relative frequency values as probabilities (they sum to ~1) and generate a random sample of letters

In [100]:
letters = np.array(list(letter_freq.keys()))
probabilities = np.array(list(letter_freq.values()))
chosen = np.random.choice(letters, 1000, p=probabilities)
''.join(chosen)

'u rkb ny iohf.oiadrahuao w lhmd,ukt i etcly hgyg teedeiswi nnoeanoaporsrnw.oarpahhbhlfse apdoee    rtthaanlcdiwtshona nv utnilso siotfvhec eniwnereehgkwldteneo sdclssaoruarnutd  wthiw.gy ee ree w.aniso tpueecu gutlt  rfr cneut s  hrgi  t oiiwnrthki  tnot,,conelrt scot teiimotouvevrdnieeobtfb evuu m ph  darsowhtth.wtsyiaroupe owt,ah ohf    hui ias wa teh ytogpfoog h inohtaoefskceuprlutyiacelk smedetobihdptgw rr nlnabie,em dttypol efthoyhn dyenra lhonoeosstau oornhklo t ss  hnmnefaieeyl lthwuecanwasidro n eh bv sde  bdrni ldkhriheat d.whhileo relb.pe itm  eichuhli bpu aei h ei iotsyd evoerioe atcjo,nwmto.lhodhel d,rf a  niisoswglln neihtadr .rtscyehmhceotfrc wm arna n,ddomc  eicmindywrd oeac eeaenivr  bo  etuyykhi p hsrsr,om is h h t n,tr fr j orlslnbitkuyo,iurte.aeattatetes a uhoew nofs  tis,iptlwh  iofsi  plrdgae l y da,e irdos hnsaewsu  a si dmut bd s tvw    xi  toog eh soh shoa rbas niapdhri doei h   e  ps aurhvecdebrttnhpohc  hwl   s ev eftdotliifwe ieadkerai  blu  ,h atootp sof ln

### Footnotes
[1]<span id="fn1"> If you dig deep enough in some of the numpy/scipy code you will find that the actual instructions you are executing were compiled from fortran and C. In general you can pass things quite easily between existing libraries and python, but fortran and C use different storage orders for multi-dimensional arrays so you have to be a little bit careful_.</span>